backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  repo: climate-tech-handbook/climate-tech-handbook

# These lines should *not* be indented
publish_mode: editorial_workflow
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: solutions # Used in routes, e.g., /admin/collections/blog
  label: "Solutions" # Used in the UI
  folder: "/docs/" # The path to the folder where the documents are stored
  extension: md
  identifier_field: slug
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - label: "Tags"
      name: "tags"
      widget: "list"
- name: blog
  label: "Blog"
  folder: docs/blog/posts
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
    - label: "Authors"
      name: "authors" 
      widget: "list"
      fields:
        - { name: name, label: Name, widget: string }
        - { name: description, label: Description, widget: string } 
        - { name: avatar, label: Avatar, widget: string }